services:
  # ==========================================================
  # POSTGRES
  # Airflow metadata database
  # ==========================================================

  dezm2h_airflow_postgres:
    image: postgres:16
    container_name: osint-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - osint

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ==========================================================
  # AIRFLOW 3 INIT
  # ==========================================================

  dezm2h_airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: osint-airflow-init

    depends_on:
      dezm2h_airflow_postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

    entrypoint: /bin/bash

    command:
      - -c
      - |
        set -e

        echo "======================================"
        echo "Airflow database migration"
        echo "======================================"

        airflow db migrate

        echo "======================================"
        echo "Creating admin user"
        echo "======================================"

        airflow users create \
          --username ${AIRFLOW_USER} \
          --password ${AIRFLOW_PASSWORD} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

        echo "======================================"
        echo "Airflow initialization complete"
        echo "======================================"

    networks:
      - osint


  # ==========================================================
  # AIRFLOW 3 API SERVER
  # ==========================================================

  dezm2h_airflow-apiserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: osint-airflow

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

    ports:
      - "8081:8080"

    command:
      - api-server

    networks:
      - osint

  # ==========================================================
  # AIRFLOW 3 SCHEDULER
  # ==========================================================

  dezm2h_airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: osint-airflow-scheduler

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

    command:
      - scheduler

    networks:
      - osint

  # ==========================================================
  # AIRFLOW 3 DAG PROCESSOR
  # ==========================================================

  dezm2h_airflow-dag-processor:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    container_name: osint-airflow-dag-processor

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

    command:
      - dag-processor

    networks:
      - osint

  # ==========================================================
  # POSTGRES
  # Homework database
  # ==========================================================

  dezm2h_postgres:
    image: postgres:18
    container_name: homework-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    networks:
      - homework

    depends_on:
      dezm2h_airflow:
        condition: service_started

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 30s
      timeout: 10s
      retries: 10

  # ==========================================================
  # PGADMIN
  # ==========================================================

  dezm2h_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dezm2h_postgres
    restart: unless-stopped

    networks:
      - homework

  # # ==========================================================
  # # HOMEWORKS
  # # ==========================================================

# ==========================================================
# NETWORK
# ==========================================================

networks:
  homework:
    driver: bridge


# ==========================================================
# PERSISTENT VOLUMES
# ==========================================================

volumes:
  postgres_data:
  pgadmin_data:
  kestra_postgres_data:
  kestra_data:
  kestra_tmp:
