services:
  # ==========================================================
  # LOCALSTACK
  # ==========================================================

  dezm2h_localstack:
    image: localstack/localstack:4.10

    ports:
      - "4566:4566"

    environment:
      SERVICES: s3
      DEBUG: "0"
      PERSISTENCE: "1"
      AWS_DEFAULT_REGION: us-east-1

    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      homework:
        aliases:
          - localhost.localstack.cloud

  # ==========================================================
  # POSTGRES
  # Airflow metadata database
  # ==========================================================

  dezm2h_airflow_postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}

    volumes:
      - airflow_postgres_data:/var/lib/postgresql

    networks:
      - homework
    
    ports:
      - "5433:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AIRFLOW_POSTGRES_USER} -d ${AIRFLOW_POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ==========================================================
  # AIRFLOW 3 INIT
  # ==========================================================

  dezm2h_airflow-init:
    build:
      context: .
      dockerfile: ./flows/module_redo_airflow/Dockerfile

    depends_on:
      dezm2h_airflow_postgres:
        condition: service_healthy
      dezm2h_postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@dezm2h_airflow_postgres:5432/${AIRFLOW_POSTGRES_DB}

      HOMEWORK_POSTGRES_HOST: dezm2h_postgres
      HOMEWORK_POSTGRES_PORT: 5432
      HOMEWORK_POSTGRES_DB: ${POSTGRES_DB}
      HOMEWORK_POSTGRES_USER: ${POSTGRES_USER}
      HOMEWORK_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./flows/module_redo_airflow/dags:/opt/airflow/dags
      - ./flows/module_redo_airflow/logs:/opt/airflow/logs
      - ./flows/module_redo_airflow/plugins:/opt/airflow/plugins

    entrypoint: /bin/bash

    command:
      - -c
      - |
        set -e

        echo "======================================"
        echo "Airflow database migration"
        echo "======================================"

        airflow db migrate

        echo "======================================"
        echo "Creating admin user"
        echo "======================================"

        airflow users create \
          --username ${AIRFLOW_USER} \
          --password ${AIRFLOW_PASSWORD} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

        echo "======================================"
        echo "Airflow initialization complete"
        echo "======================================"

    networks:
      - homework


  # ==========================================================
  # AIRFLOW 3 API SERVER
  # ==========================================================

  dezm2h_airflow-apiserver:
    build:
      context: .
      dockerfile: ./flows/module_redo_airflow/Dockerfile

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@dezm2h_airflow_postgres:5432/${AIRFLOW_POSTGRES_DB}
      
      AIRFLOW_CONN_HOMEWORK_POSTGRES: >-
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dezm2h_postgres:5432/${POSTGRES_DB}

      AIRFLOW_CONN_LOCALSTACK: >-
        aws://test:test@/?endpoint_url=http%3A%2F%2Flocalhost.localstack.cloud%3A4566&region_name=eu-central-1

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}

    volumes:
      - ./flows/module_redo_airflow/dags:/opt/airflow/dags
      - ./flows/module_redo_airflow/logs:/opt/airflow/logs
      - ./flows/module_redo_airflow/plugins:/opt/airflow/plugins

    ports:
      - "8081:8080"

    command:
      - api-server

    networks:
      - homework

  # ==========================================================
  # AIRFLOW 3 SCHEDULER
  # ==========================================================

  dezm2h_airflow-scheduler:
    build:
      context: .
      dockerfile: ./flows/module_redo_airflow/Dockerfile

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@dezm2h_airflow_postgres:5432/${AIRFLOW_POSTGRES_DB}
      
      AIRFLOW_CONN_HOMEWORK_POSTGRES: >-
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dezm2h_postgres:5432/${POSTGRES_DB}

      AIRFLOW_CONN_LOCALSTACK: >-
        aws://test:test@/?endpoint_url=http%3A%2F%2Flocalhost.localstack.cloud%3A4566&region_name=eu-central-1

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}

      AIRFLOW__API__BASE_URL: http://dezm2h_airflow-apiserver:8080

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://dezm2h_airflow-apiserver:8080/execution/

    volumes:
      - ./flows/module_redo_airflow/dags:/opt/airflow/dags
      - ./flows/module_redo_airflow/logs:/opt/airflow/logs
      - ./flows/module_redo_airflow/plugins:/opt/airflow/plugins

    command:
      - scheduler

    networks:
      - homework

  # ==========================================================
  # AIRFLOW 3 DAG PROCESSOR
  # ==========================================================

  dezm2h_airflow-dag-processor:
    build:
      context: .
      dockerfile: ./flows/module_redo_airflow/Dockerfile

    depends_on:
      dezm2h_airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@dezm2h_airflow_postgres:5432/${AIRFLOW_POSTGRES_DB}
      
      AIRFLOW_CONN_HOMEWORK_POSTGRES: >-
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dezm2h_postgres:5432/${POSTGRES_DB}

      AIRFLOW_CONN_LOCALSTACK: >-
        aws://test:test@/?endpoint_url=http%3A%2F%2Fdezm2_localstack%3A4566&region_name=eu-central-1

      AIRFLOW__CORE__AUTH_MANAGER: >-
        airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./flows/module_redo_airflow/dags:/opt/airflow/dags
      - ./flows/module_redo_airflow/logs:/opt/airflow/logs
      - ./flows/module_redo_airflow/plugins:/opt/airflow/plugins

    command:
      - dag-processor

    networks:
      - homework

  # ==========================================================
  # POSTGRES
  # Homework database
  # ==========================================================

  dezm2h_postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      - "5432:5432"

    volumes:
      - homework_postgres_data:/var/lib/postgresql

    networks:
      - homework

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 30s
      timeout: 10s
      retries: 10

  # ==========================================================
  # PGADMIN
  # ==========================================================

  dezm2h_pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dezm2h_postgres
    restart: unless-stopped

    networks:
      - homework

# ==========================================================
# NETWORK
# ==========================================================

networks:
  homework:
    driver: bridge


# ==========================================================
# PERSISTENT VOLUMES
# ==========================================================

volumes:
  airflow_postgres_data:
  homework_postgres_data:
  pgadmin_data:
  localstack_data:
